### ISSUE TITLE
Add support for a RepositoryMap.json

### ISSUE THREAD

**Issue by Ardesco** [Ardesco/selenium-standalone-server-plugin#19]
Just because json is so much nicer than xml.

**Comment by Ardesco** [comment]
Or maybe YAML, or TOML...

**Comment by haroon-sheikh** [comment]
@Ardesco I've started working on this with YAML which looks a bit like this?

```
windows:
  -
    name: chromedriver
    version: 2.33
    fileLocation: https://chromedriver.storage.googleapis.com/2.33/chromedriver_win32.zip
    hash: f6a0d7939355acba00f7b1374bebda50bbead59b
    hashType: sha1
    bitrate:
      - 32bit
      - 64bit
osx:
  -
    name: chromedriver
    version: 2.33
    fileLocation: https://chromedriver.storage.googleapis.com/2.33/chromedriver_win32.zip
    hash: f6a0d7939355acba00f7b1374bebda50bbead59b
    hashType: sha1
    bitrate:
      - 32bit
      - 64bit
```

Are we happy with YAML? if yes, shall we deprecate xml completely and plan `2.0.0` of the plugin?
